services:
  external:
    image: {SOUT}
    ports: ["3000:3000"]
    env_file:
      - .env
    volumes:
      - "./data:/data"
      - "./queries-metadata:/queries-metadata"
    environment:
      - RACK_ENV=production
      - APP_ENV=production     # both for redundancy

