version: '3.9'
services:
  internal:
    build: ./internal
    environment:
      - EXTERNAL_URL=http://external:4567
      - TRIPLESTORE_URL=http://your-triplestore:3030/sparql
      - ENCRYPTION_KEY_HEX=...
      - RESULT_FORMAT=json
