services:
  external:
#    build: ./
    image: outie
    ports: ["3000:3000"]
    env_file:
      - .env
    volumes:
      - "./data:/data"
      - "./queries-metadata:/metadata"
    # ... other settings
    environment:
      - RACK_ENV=production
      - APP_ENV=production     # both for redundancy
      - METADATA_DIR=/metadata

